### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by yuraM18** [yuraM18/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by yura-mukomel** [comment]
**### My name is Elon Musk and everyone thinks I'm a genius, billionaire, playboy, philanthropist. But in fact, this is an alien who came to us from another galaxy, crashing his spaceship during landing, and is desperately trying to pull up the local progress in order to quickly dump home.**
