### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by yuraM18** [yuraM18/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by yura-mukomel** [comment]
**### Elon Musk**
https://twitter.com/elonmusk
https://twitter.com/Tesla
https://twitter.com/SpaceX
