### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by yuraM18** [yuraM18/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by yura-mukomel** [comment]
EXPERIENCE

**2021**
Tesla bought $ 1.5 billion worth of bitcoins

**2018**
A test flight of the Falcon Heavy - the most powerful missile at the moment

**2016**
Presented a new budget model - Tesla Model 3
Musk co-founded Neuralink

**2015**
It was possible to carry out a controlled descent and landing of the first stage of the missile on the ground

**2012**
 Dragon docked with the ISS for the first time
Presented the first version of the rocket for the study and colonization of Mars

**2009**
 For the first time, a Malaysian satellite was launched into orbit

**2008**
The first car available for sale is the Tesla Roadster

**2007**
Tesla almost went bankrupt

**2006**
Failed tests of the first launch vehicle SpaceX - Falcon 1

**2003**
Tesla Motors was founded

**2002**
In June, Musk founded his third company, SpaceX
In October, PayPal was bought by eBay for $ 1.5 billion. At the time of the sale, Mask owned 11.7% of the company's shares, which allowed him to invade $ 165 million.

**2000**
X.com and Confinity merged, one of which was called PayPal

**1999**
Zip2 was bought out by Compaq, paying $ 304 million to Ilona Maska, whose share in the company at the time was 7%, or $ 22 million.
In March, Musk co-founded X.com.

**1995**
The first company Zip2 was founded

**1989**
He worked as a cleaner for $ 18 an hour

**1981**
He sold his first game called Blastar for $ 500

**1971**
Born into a family of engineers and models


PERSONAL LIFE

**2020**
Grimes gave birth to their first child, Ilona Mask
Child's name "X Æ A-12 Musk"

**2018**
At the Met Gala, Musk appeared in public with Canadian singer Grimes

**2017**
He met actress Amber Heard

**2016**
Break

**2010**
He married British actress Tallulah Riley

**2008**
Break

**2002**
The long-awaited firstborn was born - a boy named Nevada Alexander

**2000**
Justin and Elon married
