### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by yuraM18** [yuraM18/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by yura-mukomel** [comment]
LANGUAGES
us ENGLISH ru РУССКИЙ

PRINCIPLES OF SUCCESS
1. It's not about money
2. Follow what fascinates you
3. Do not be afraid to set large-scale tasks
4. Don't be afraid to take risks
5. Ignore criticism
6. Have fun

CHARACTER

Elon Musk is a workaholic. He likes to work at night, and has repeatedly admitted that he would refuse to eat if it were possible
